#!/usr/bin/env node
"use strict";

import path from "path";
import fs from "fs/promises";
//const path = require("path");
//const fs = require("fs/promises");

const basePath = "src/dist/";

(async function(){
	const moduleDir = "./node_modules/shogicross/src/dist";
	const pack = JSON.parse(await fs.readFile("./package.json", "utf8"));
	const entry = pack.main ?? "./";
	const entryDir = path.dirname(entry);

	const cpFiles = ["json/", "img/"];
	await Promise.all(
		cpFiles.map(async f=>{
			const moduleFiles = path.join(moduleDir, f);
			const entryFiles = path.join(entryDir, f);
			return fs.cp(moduleFiles, entryFiles, {recursive: true})
		})
	);
	console.log("ShogiCross init Success!");
})();
