name: Build Tauri App

on:
  push:
    branches:
      - tauri
  workflow_run:
    workflows: ["Build and Deploy"]  # Workflow A の名前
    types:
      - completed

jobs:
  BuildAppWindows:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: windows-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache NPM Modules
        uses: actions/cache@v4
        with:
          path: app/node_modules
          key: ${{hashFiles('app/package.json')}}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            app/src-tauri/target
          key: ${{hashFiles('app/src-tauri/Cargo.lock')}}

      - name: Setup NPM Modules
        run: npm install

      - name: Build Tauri App
        run: npm run tauri build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: app/src-tauri/target/release/*.exe

  BuildAppLinux:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache NPM Modules
        uses: actions/cache@v4
        with:
          path: app/node_modules
          key: ${{hashFiles('app/package.json')}}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            app/src-tauri/target
          key: ${{hashFiles('app/src-tauri/Cargo.lock')}}

      - name: Setup Linux Liblary
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Setup NPM Modules
        run: npm install

      - name: Build Tauri App
        run: npm run tauri build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-linux
          path: app/src-tauri/target/release/bundle/appimage/*.AppImage

  BuildAppAndroid:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache NPM Modules
        uses: actions/cache@v4
        with:
          path: app/node_modules
          key: ${{hashFiles('app/package.json')}}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            app/src-tauri/target
          key: ${{hashFiles('app/src-tauri/Cargo.lock')}}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Export Android Env
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "NDK_HOME=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_ENV

      - name: Install NPM Modules
        run: npm install

      - name: Setup Tauri App
        run: npx tauri android init

      - name: Build Tauri App
        run: npx tauri android build --apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-android
          path: app/src-tauri/gen/android/app/build/outputs/apk/universal/release/*.apk
