name: Create and Push Tag from package.json (if-conditional)

on:
  push:
    branches:
      - act

jobs:
  tag-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get ShogiCross Version
        id: PROJECT_VERSION
        run: echo "value=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      # 4. リモートリポジトリにタグが存在するかチェックするステップ
      - name: Get Tag Exists
        id: EXISTS_TAG
        run: |
          TAG_NAME="${{steps.PROJECT_VERSION.outputs.value}}"
          echo "Checking for tag ${TAG_NAME}..."
          if git ls-remote --tags origin | grep -q "refs/tags/${TAG_NAME}"; then
             echo "Tag ${TAG_NAME} already exists."
            echo "value=true" >> $GITHUB_OUTPUT
          else
            echo "Tag ${TAG_NAME} does not exist. Ready to create."
            echo "value=false" >> $GITHUB_OUTPUT
          fi

    # 5. タグが存在しない場合 (check_tagが失敗した場合) にタグを作成
      - name: Create and Push Tag
        if: steps.EXISTS_TAG.output.value == 'true'
        run: |
          TAG_NAME="${{steps.PROJECT_VERSION.outputs.value}}"
          echo "Tag does not exist. Creating and pushing tag ${TAG_NAME}."
          # git config --global user.name 'github-actions[bot]'
          # git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # git tag $TAG_NAME
          # git push origin $TAG_NAME

      # 6. タグが既に存在する場合 (check_tagが成功した場合) にメッセージを表示
      - name: Log that tag already exists
        if: steps.EXISTS_TAG.output.value == 'false'
        run: |
          TAG_NAME="${{ steps.PROJECT_VERSION.outputs.value }}"
          echo "Tag ${TAG_NAME} already exists. Skipping creation."