name: Create and Push Tag from package.json (if-conditional)

on:
  push:
    branches:
      - act

jobs:
  tag-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      # 4. リモートリポジトリにタグが存在するかチェックするステップ
      - name: Check if tag exists
        id: check_tag # このステップの出力を参照するためにIDを設定
        run: |
          TAG_NAME="v${{ steps.get_version.outputs.VERSION }}"
          # git ls-remoteの終了コードを使ってタグの存在を確認
          if git ls-remote --tags origin | grep -q "refs/tags/${TAG_NAME}"; then
            echo "Tag ${TAG_NAME} already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag ${TAG_NAME} does not exist. Ready to create."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      # 5. 前のステップの結果を使い、タグが存在しない場合のみこのステップを実行
      - name: Create and Push Tag
        if: steps.check_tag.outputs.exists == 'false' # if条件
        run: |
          TAG_NAME="${{ steps.get_version.outputs.VERSION }}"
          echo "Creating and pushing tag ${TAG_NAME}"
