name: Build Tauri App

on:
  push:
    branches:
      - tauri
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: tauri

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Install npm dependencies
        run: npm install
      - name: Build Tauri for Linux
        run: |
          npm run tauri build
          rm -rf dist src-tauri/target/release/bundle/appimage/shogicross-app.AppDir

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-linux
          path: tauri/src-tauri/target/release/bundle/appimage

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: tauri

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri for Windows
        run: npm run tauri build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows
          path: tauri/src-tauri/target/release/shogicross.exe
